version: 2
jobs:
  testing:
    docker:
    - image: circleci/node:latest
    steps:
    - checkout
    - run: npm test

  linting:
    docker:
    - image: circleci/node:latest
    steps:
    - checkout
    - npm run lint

workflows:
  version: 2
  one_and_two:
    jobs:
    - testing
    - linting
